artifacts_root: artifacts # Note: This line must also be a key: value pair

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://github.com/proshanta000/project_data/raw/refs/heads/main/winequality.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion


data_validation:
    root_dir: artifacts/data_validation
    unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
    STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
    root_dir: artifacts/data_transformation
    data_path: artifacts/data_transformation/winequality-red.csv

model_trainer:
    root_dir: artifacts/model_trainer
    train_data_path: artifacts/data_transformation/train.csv
    test_data_path: artifacts/data_transformation/test.csv
    model_name: model.jonlib
    